
services:
  backend:
    build: 
      context: ./  # Path to your backend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/flightbooking
    volumes:
      - ./flight-booking-backend:/app
    depends_on:
      - mongo


  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
